### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by wazaraki**
Hello all,

This uses spaces instead of tabs to better comply with project's coding standard. Also cleans up some trailing whitespaces.

I hope these changes aren't too bad or worthless. :)

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@wazaraki__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by msotclas** [comment]
__@wazaraki__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by mattpodwysocki** [comment]
@wazaraki please do not check in the /dist files.  Please remove them before I can accept this PR.  Looks great otherwise!

**Comment by mattpodwysocki** [comment]
@wazaraki thanks!  Merged!

**Pull request merged**
