### PR TITLE
HistoricalScheduler's constructor params are both optional

### PR DESCRIPTION
**Pull request by raybooysen**
A fix for the documentation and a change to the .d.ts file for HistoricalScheduler as initialClock and comparer are both optional.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@raybooysen__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by raybooysen** [comment]
I followed the getting contributing guide which asked for a full grunt run.  This has re-generated all the dist files.  Unsure if this is correct, can remove if required.

**Comment by msotclas** [comment]
__@raybooysen__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by raybooysen** [comment]
Rebasing the PR so only the docs are changed.

**Pull request merged**
