### PR TITLE
Feature: Add Observable.prototype.singleInstance()

### PR DESCRIPTION
**Pull request by blesh**
Relates to discussion here: #487

First pass: 

- add operator
- add tests

Todo:

- docs

Just waiting for review before I add the documentation.

### CODE REVIEW

**Comment by paulpdaniels** [comment]
perhaps remove the mergelatest operator from this PR?

Also I wasn't quite sure from your discussion what is was that you are passing through the singleInstance operator, is it the websocket subject?

```javascript 

Rx.DOM.fromWebsocket(url).singleInstance();

```
If that is the case, I would think publishValue() might be a better option since after the observable goes hot subsequent, observers will only get onCompleted or onError messages.

Like the proposal though, I think it would solve some of the hacks I have done around maintaining real-time connections.

**Comment by blesh** [comment]
@paulpdaniels - The source of me needing this pattern a lot is the Rx web socket implementation which is a Subject that wraps a WebSocket. When this subject is subscribed to, it creates the underlying socket and connects. On disposal, it disconnects the socket. 

Now, most of the time, you only want a *single*, shared socket connection to a single server. So you don't want to go creating N connections to the same endpoint where N is the number of observables you've branched off of your socket. 

So the first solution is  a `publish()` and `connect()`, but in a system without an apparent ideal location for that `connect()` call (say a complicated SPA or something), you're better off with a `publish().refCount()`, which works great, until the first time you dispose of everything streaming from your socket, then the socket closes and your socket observable cannot be reopened because you can't resubscribe to the underlying observable of a `publish().refCount()`. :(

So I ended up (multiple times, for similar reasons) creating an Observable that when I subscribe to it produces a new, published, refCounted observable on subscription if it doesn't already have one that's ready to go.

Made generic, this is the `singleInstance` operator. And despite a LOT of fiddling, this has been the only great method I've found to do what I need to do.

**Comment by blesh** [comment]
> remove the mergeLatest operator from this PR

What do you mean here? I don't recall adding a mergeLatest or touching one?

**Comment by blesh** [comment]
Oh, weird, I see. I don't recall adding this. I wonder where it came from? Thanks, @paulpdaniels for that catch. (This is why Pull Requests work)

**Comment by blesh** [comment]
Removed the silly code file I had added weeks ago and forgotten about. :\

**Comment by mattpodwysocki** [comment]
@blesh did you sign the CLA yet?

**Comment by blesh** [comment]
@mattpodwysocki - I had to forward the agreement to Netflix legal. :(  OSS CLA's that include employers.

**Comment by blesh** [comment]
@mattpodwysocki - I'm sure it will all be straightened out by tomorrow.

**Comment by Igorbek** [comment]
May be better to introduce reconnactable observables?

**Comment by blesh** [comment]
@Igorbek that's effectively what this is doing. I didn't see a need to subclass Observable to do so though, since there are no special methods or operators required.

**Comment by blesh** [comment]
@mattpodwysocki - I'm still waiting for legal to review the CLA. :\  Hopefully it will be done soon.

**Comment by mattpodwysocki** [comment]
@blesh any update? Also, did you add docs yet for this?

**Comment by blesh** [comment]
No docs yet. Wanted to make sure it was desired first.

**Comment by msotclas** [comment]
__@blesh__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by blesh** [comment]
So... My wife and I just had a baby. I'll get to the documentation for this in the next week or so. If I don't pester me. :P

**Comment by blesh** [comment]
Just added the docs. Given I'm sleep deprived, it's probably a good idea to review them. :P

**Comment by cboden** [comment]
Congratulations @blesh!

Also love the `singleInstance` operator, been using it for a couple weeks now. :+1:

**Comment by blesh** [comment]
Thanks!

**Pull request merged**
