### PR TITLE
Added Typescript definitions for selectManyObserver and flatMapObserver on Observable

### PR DESCRIPTION
**Pull request by athasach**

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@athasach__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by Igorbek** [comment]
Looks good except of on one thing.
How the result type can be inferred? It seems all the selectors should return `Observable<R>`.
_Or_, the result can be `Observable<T1|T2|T3>` but if you omit any of selector it will be inferred as not desirable `Observable<any>`.

**Comment by athasach** [comment]
@Igorbek Good point. I've adjusted the code to use a return type of Observable<T2|T3|T4> instead of Observable<R>.

**Comment by mattpodwysocki** [comment]
@athasach ok, looks great.  Can you sign the CLA as in the link above so we can get it merged in?

**Comment by Igorbek** [comment]
Personally, I prefer to turn all selectors to `Observable<R>`, it makes more sense. Or, at least, add it as additional overload (which comes first).

**Comment by athasach** [comment]
@mattpodwysocki I'm working with my employer to get the necessary permissions to sign the CLA.

**Comment by athasach** [comment]
@Igorbek What is the advantage of using ```Observable<R>``` instead? I'm not sure how I might make ```R``` an additional overload.

**Comment by msotclas** [comment]
__@athasach__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by mattpodwysocki** [comment]
@Igorbek I'm ok with accepting as is, what say you?

**Pull request merged**
