### PR TITLE
Add "typings" entry

### PR DESCRIPTION
**Pull request by whitecolor**
Add "typings" entry to rx.all.d.ts

### CODE REVIEW

**Comment by whitecolor** [comment]
@mattpodwysocki this this is kind of must?

**Comment by whitecolor** [comment]
Hello!

**Comment by MeirionHughes** [comment]
could this be published to npm as a patch please?

**Comment by whitecolor** [comment]
@mattpodwysocki 

Pleas publish this on NPM, with it just creates exessive hurdle for those who want to use `rx`.

**Pull request merged**
