### PR TITLE
Added singleInstance to build process

### PR DESCRIPTION
**Pull request by jonahbron**
The relatively new singeInstance observable was not in the build process, and so un-usable as far as I could see.  This adds it.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@jonahbron__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by mattpodwysocki** [comment]
@jonahbron I'm not quite sure of the use and it doesn't seem super useful to me yet.

**Comment by jonahbron** [comment]
@mattpodwysocki Okay.  Why was the operator merged if it's not going to be used?  Is there a way for me to use it without maintaining my own fork?

**Comment by mattpodwysocki** [comment]
@jonahbron can you please remove the /dist from this pull request and sign the CLA so we can merge it?

**Comment by msotclas** [comment]
__@jonahbron__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by jonahbron** [comment]
@mattpodwysocki Sounds good, all done.

**Comment by mattpodwysocki** [comment]
@jonahbron made a few changes so this won't be necessary.  It's now in `rx.all.js`, `rx.all.compat.js`, `rx.binding.js`, `rx.lite.extras.js` and `rx.lite.extras.compat.js`

**Comment by jonahbron** [comment]
@mattpodwysocki Sweet, thank you.

**Pull request closed without merging**
