### PR TITLE
Dispose outer retrywhen subscription after error

### PR DESCRIPTION
**Pull request by paddlefish**
Fixes issue #1009

### CODE REVIEW

**Comment by paddlefish** [comment]
@msotclas : What is "cal-required"?  Is there anything I can do to help move this PR along?

**Comment by msotclas** [comment]
__@paddlefish__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by paddlefish** [comment]
I rebased this on master since it's been sitting here a while, and verified that the unit tests still pass.

**Comment by paddlefish** [comment]
yay! Thanks, @mattpodwysocki . I'm glad that RxJava and RxSwift will be consistent on this behavior now.

**Comment by mattpodwysocki** [comment]
@paddlefish no problem, although I changed the `SerialDisposable` back to `SingleAssignmentDisposable` but actually dispose it instead of `setDisposable(null)` which would do the same thing

**Comment by paddlefish** [comment]
Good to know.  Trying to keep these lifetime best practices straight between RxJava and RxJS and RxSwift keeps me on my toes for sure. :)  Cheers.

**Pull request merged**
