### PR TITLE
Fixed IE8 issue in defaultScheduler.js : the variable 'currentId' is undefined

### PR DESCRIPTION
**Pull request by amoerie**
While testing an app in IE8, the following issue arose:

SCRIPT5009: 'currentId' is undefined

The culprit was hiding inside rx.all.compat.js at the following line:

    scheduleMethod = function (action) {
        var id = nextHandle++;
        tasksByHandle[id] = action;
        root.postMessage(MSG_PREFIX + currentId, '*'); // THIS GUY HERE
        return id;
    };

I traced the problem back to [this commit](https://github.com/Reactive-Extensions/RxJS/commit/5555090ec1524178c417a8f0f7cf846cb85b4040) that renamed that variable everywhere to 'id', except in this one place.

The tests are all green. Running the tests seems to have introduced some changes though that I am not responsible for. Is it possible that you have not ran the tests after every commit?

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@amoerie__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, MSOTBOT;

**Comment by amoerie** [comment]
... You work fast. Did you really just merge this PR within 30 seconds of its creation?

**Comment by mattpodwysocki** [comment]
@amoerie yep, because I knew it was broken and thanks for the fix!

**Comment by amoerie** [comment]
Alrightie! Thank you for the great library, really loving it so far!

**Pull request merged**
